import "dotenv/config";
import { z } from "zod";

const envSchema = z.object({
  API_PORT: z.coerce.number().int().positive().default(4000),
  DATABASE_URL: z.string().min(1).optional(),
  DATABASE_FILE: z.string().default("./data/concierge.sqlite"),
  DASHBOARD_ORIGIN: z.string().default("http://localhost:3000"),
  ARTICLES_PER_SOURCE: z.coerce.number().int().min(1).max(100).default(25),
  INGEST_CRON: z.string().default("*/30 * * * *"),
  DELIVERY_CRON: z.string().default("0 */4 * * *"),
  DELIVERY_COUNT: z.coerce.number().int().min(1).max(10).default(3),
  SERENDIPITY_THRESHOLD: z.coerce.number().min(0).max(1).default(0.88),
  SERENDIPITY_PROBABILITY: z.coerce.number().min(0).max(1).default(0.35),
  RUN_INGESTION_ON_START: z.enum(["true", "false"]).default("false"),
  ADMIN_CHANNEL_ID: z.string().default("admin-preview"),
  ADMIN_CHANNEL_NAME: z.string().default("dashboard-preview"),
  RANKING_ALGORITHM: z.string().min(1).default("interpretable-linear-v1"),
  LLM_PROVIDER: z.enum(["openai", "disabled"]).default("openai"),
  LLM_WEIGHT: z.coerce.number().min(0).max(1).default(0.3),
  LLM_CANDIDATE_LIMIT: z.coerce.number().int().min(0).max(25).default(2),
  OPENAI_API_KEY: z.string().optional(),
  OPENAI_BASE_URL: z.string().url().default("https://api.openai.com/v1"),
  OPENAI_MODEL: z.string().min(1).default("gpt-5.6"),
  OPENAI_MODEL_REVISION: z.string().default("1"),
  OPENAI_TIMEOUT_MS: z.coerce.number().int().min(1000).max(600000).default(120000),
  INFERENCE_ADMIN_TOKEN: z.string().optional(),
  INFERENCE_SETTINGS_KEY: z.string().optional(),
  DISCORD_BOT_TOKEN: z.string().optional(),
});

const parsed = envSchema.parse(process.env);

export const config = {
  apiPort: parsed.API_PORT,
  databaseUrl: parsed.DATABASE_URL,
  databaseFile: parsed.DATABASE_FILE,
  dashboardOrigin: parsed.DASHBOARD_ORIGIN,
  articlesPerSource: parsed.ARTICLES_PER_SOURCE,
  ingestCron: parsed.INGEST_CRON,
  deliveryCron: parsed.DELIVERY_CRON,
  deliveryCount: parsed.DELIVERY_COUNT,
  serendipityThreshold: parsed.SERENDIPITY_THRESHOLD,
  serendipityProbability: parsed.SERENDIPITY_PROBABILITY,
  runIngestionOnStart: parsed.RUN_INGESTION_ON_START === "true",
  adminChannel: { id: parsed.ADMIN_CHANNEL_ID, name: parsed.ADMIN_CHANNEL_NAME },
  rankingAlgorithm: parsed.RANKING_ALGORITHM,
  llmProvider: parsed.LLM_PROVIDER,
  llmWeight: parsed.LLM_WEIGHT,
  llmCandidateLimit: parsed.LLM_CANDIDATE_LIMIT,
  openAiBaseUrl: parsed.OPENAI_BASE_URL,
  openAiModelRevision: parsed.OPENAI_MODEL_REVISION,
  openAiTimeoutMs: parsed.OPENAI_TIMEOUT_MS,
  openAiApiKey: parsed.OPENAI_API_KEY,
  openAiModel: parsed.OPENAI_MODEL,
  inferenceAdminToken: parsed.INFERENCE_ADMIN_TOKEN,
  inferenceSettingsKey: parsed.INFERENCE_SETTINGS_KEY,
  discord: {
    enabled: Boolean(parsed.DISCORD_BOT_TOKEN),
    token: parsed.DISCORD_BOT_TOKEN,
  },
};
